defaults: 
 - default
 - override /model/components/sequence_models@models_config.sequence_model_xz: cnn # cnn or bart
 - override /model/components/sequence_models@models_config.sequence_model_zx: cnn # vision_transformer or vision_transformer_pretrained
 - override /model/components/symbolic_bottlenecks@models_config.symbolic_autoencoder_wrapper_xzx: bart_bart
 - override /model/components/symbolic_bottlenecks@models_config.symbolic_autoencoder_wrapper_zxz: bart_bart
 - override /model/components/discretizers@models_config.discretizer_x: softmaxDB
 - override /model/components/discretizers@models_config.discretizer_z: identity

_target_: src.models.sigmae_lit_module_im_to_text_fullcnn.SigmaeLitModuleImageToTextFullCNN

#here z is the image and x is the text

models_config:

  sequence_model_xz: #txt to img
    config:
      input_size: ${mult_int:${model.model_params.max_x_length},${model.model_params.d_model}}
      output_length: 
        - ${model.model_params.num_channels}
        - ${model.model_params.image_size}
        - ${model.model_params.image_size}

    model:
      in_channels: ${model.model_params.max_x_length}
      out_channels: ${model.model_params.num_channels}
      # num_layers: 6
      up_block_types: 
        # - ResnetBlock2D
        # - ResnetBlock2D
        - UpDecoderBlock2D
        - UpDecoderBlock2D

      block_out_channels:
        - 64
        - 64

      layers_per_block: 2
      norm_num_groups: 32
      act_fn: silu
      # norm_type: group
      mid_block_add_attention: true

  sequence_model_zx:
    config:
      input_size: ${mult_int:${model.model_params.image_size},${model.model_params.image_size}}
      output_length: 
        - ${model.model_params.max_x_length}
        - ${model.model_params.d_model}
      inherit_model_embedding_weights_for_discretizers: false
    
    model:
      _target_: diffusers.models.autoencoders.vae.Encoder
      in_channels: ${model.model_params.num_channels}
      out_channels: ${model.model_params.max_x_length}
      # num_layers: 6
      down_block_types: 
        # - ResnetBlock2D
        # - ResnetBlock2D
        - DownEncoderBlock2D
        - DownEncoderBlock2D

      block_out_channels:
        - 64
        - 64

      layers_per_block: 2
      norm_num_groups: 32
      act_fn: silu
      double_z: false
      # norm_type: group
      mid_block_add_attention: true

    processor:
      _target_: transformers.ViTImageProcessor
      do_normalize: true
      do_rescale: true
      do_resize: true
      image_mean: ${model.model_params.processor.image_mean} #in function of of image and number of channels
      image_processor_type: “ViTImageProcessor”
      image_std: ${model.model_params.processor.image_std}
      resample: 2
      rescale_factor: 0.00392
      size: ${model.model_params.processor.image_size}

  discretizer_x:
    config:
        dimensions:
          encoder_embedding_dim: ${model.model_params.d_model}
          decoder_embedding_dim: ${model.model_params.d_model}
          unembedding_dim: ${model.model_params.d_model} #3 or 1 channels
          vocab_size: ${model.model_params.x_vocab_size} #3 or 1 channels
          
  discretizer_z:
    config:
      dimensions:
        encoder_embedding_dim: ${model.model_params.d_model}
        decoder_embedding_dim: ${model.model_params.d_model}
        unembedding_dim: ${mult_int:${model.model_params.z_patch_size},${model.model_params.num_channels}} #3 or 1 channels
        vocab_size: ${mult_int:${model.model_params.z_patch_size},${model.model_params.num_channels}} #3 or 1 channels
    
    