defaults:
  - /model/components/sequence_models@models.sequence_model_xz: default
  - /model/components/symbolic_bottlenecks@models.symbolic_autoencoder_wrapper_xzx: default
  - /model/components/sequence_models@models.sequence_model_zx: default
  - /model/components/symbolic_bottlenecks@models.symbolic_autoencoder_wrapper_zxz: default

_target_: src.models.sigmae_lit_module.SigmaAELitModule

model_params:
  max_x_length: 100
  max_z_length: 100
  compile: false # compile model for faster training with pytorch 2.0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10
