supervision_scheduler:
  _target_: src.models.callbacks.supervision_probability_callback.SupervisionProbabilitySchedulerCallback

  scheduler_xz: 
    _target_: src.utils.schedulers.linear_scheduler.LinearScheduler
    num_warmup_steps: 25
    num_training_steps: 80
    hp_init: 1.0
    hp_end: 0.2
    power: 1.0

  scheduler_z:
    # between 0 and 1, saying given that a sample is not xz, how likely is it to be z.
    _target_: src.utils.schedulers.linear_scheduler.LinearScheduler
    num_warmup_steps: 25
    num_training_steps: 80
    hp_init: 0.9
    hp_end: 0.6
    power: 1.0