_target_: symbolic_bottleneck.auto_reg_wrapper.AutoRegWrapper

config:
  inherit_model_embedding_weights_for_discretizers: true
  use_past_key_values: False
  use_last_step_states: False
  max_lengths:
    input: 45
    output: 45
  control_token_ids:
    input_pad_token_id: null
    output_eos_token_id: null 
    output_pad_token_id: null
    output_unknown_token_id: null
  soft_average:
    p_eos_backward: True
    p_eos_forward: False 
    word_embeds_with_scores_forward: True
  output_prepending_ids: null
  device: cpu

model:  ???
tokenizer:  ??? 
model_unwrapper:  ???